### ISSUE TITLE
—confirm-page-size not accepted

### ISSUE THREAD

**Issue by ih8github** [castlelemongrab/parlance#28]
When I set -p to anything (even just 11) I get the warning about —confirm-page-size followed by a fatal error even when using —confirm-page-size

**Comment by castle-lemongrab** [comment]
Should be fixed in c951419 now. Negative numbers aren't properly excluded currently due to the way the argument parsing library works, but specifying a positive integer for the option should work now. Note that using this option (i) may deviate from what the official frontend does, and (ii) may have no effect on some APIs (it's up to the server, the tool can only request it).

**Comment by castle-lemongrab** [comment]
Argument parsing and client invocation parameter consistency issues would be easy targets for unit tests, as the constraints aren't likely to change along with the server API. Schedule some of these for #10 so they don't keep getting messed up or regress.
