### ISSUE TITLE
Save json output to file

### ISSUE THREAD

**Issue by havardl** [castlelemongrab/parlance#40]
I was just wondering if there is a command to save the response from Parler to a given file, instead of printing data to console?

**Comment by pranithapat** [comment]
yes, following your desired pull just add:
`-s > filename.json`

**Comment by castle-lemongrab** [comment]
The `-s` shouldn't be strictly necessary, since any log information is printed to `stderr` instead of `stdout`. The tool currently assumes that you're using it within a shell that can do output redirection (`> file.json` to overwrite, or `>> file.json to append and create if nonexistent). You should also be able to similarly redirect the log information using `2> file.log` or `2>> file.log`.

**Comment by havardl** [comment]
Awesome, thanks!
