### ISSUE TITLE
New Authentication

### ISSUE THREAD

**Issue by chrisji** [castlelemongrab/parlance#51]
Hi!

Wondered if you're aware of any changes to Parler recently that would effect the cookie-based authentication process.

There no longer appears to be MST or JST tokens, just `PHPSESID` and `PV*` cookies. Is there potential for this codebase to make use of these instead, or does this change require a different strategy?

Cheers!

**Comment by castle-lemongrab** [comment]
Yeah, Parler ripped their whole API server out recently. The domain exists but the functionality is dead and gone. They seem to have switched over to PHP’s session management, and now appear to return server-side rendered HTML markup snippets instead of JSON.

We’ll add a deprecation notice to the tool. There are likely a lot of screen-scraping frameworks that could make quick work of Parler’s (seemingly still ongoing) rewrite, now or in the future.

I’ll always miss that `{ human: false }` field, though.

**Comment by chrisji** [comment]
Ah, sad times, but thanks for the info!

If I stumble upon a workable scraping solution, I'll revisit with findings...

Cheers @castle-lemongrab !
